server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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
