erDiagram
    UserProfile {
        string id PK "UUID"
        string userId "unique"
        string username
        string email
        string firstName
        string lastName
        string avatar
        date dob
        string city
    }